### ISSUE TITLE
[java-spring-boot] secrets template - value needs to be a string

### ISSUE THREAD

**Issue by eidottermihi** [it-at-m/helm-charts#116]
values.yaml:

```yaml
credentials:
  dummy:
    data:
      my.prop: 123
```

gives a

```
Error: template: java-spring-boot/templates/secrets.yaml:13:26: executing "java-spring-boot/templates/secrets.yaml" at <b64enc>: wrong type for value; expected string; got float64
```

-> solution: typecast all "values" to strings before going through `b64enc`
