### ISSUE TITLE
[java-spring-boot] add option to keep generated secrets

### ISSUE THREAD

**Issue by eidottermihi** [it-at-m/helm-charts#117]
When a user lets the helm chart generate the secret, e.g.:

```yaml
credentials:
  dummy:
    data:
      my.secret: "123"
```

there should be an option that those secrets are not deleted on a `helm uninstall`, using ["helm.sh/resource-policy: keep"](https://helm.sh/docs/howto/charts_tips_and_tricks/#tell-helm-not-to-uninstall-a-resource), e.g:

```yaml
credentials:
  dummy:
    keepSecret: true # default: false
    data:
      my.secret: "123"
```
