### ISSUE TITLE
[refarch-gateway]: introduce envFrom support in deployment template

### ISSUE THREAD

**Issue by langehm** [it-at-m/helm-charts#120]
We need `envFrom` in the deployment.yaml also in the refarch-gateway helm template.
With `envFrom` we can ingest complete secrets or configMaps as a whole and save some configuration inside the values.yaml, because we dont have to list each needed key from the secret or configmap separatly.

Could look like this in the deployment.yaml:
```yaml
envFrom:
  {{- toYaml $module.envFrom | nindent 12 }}
```

and like this in the values.yaml:
```yaml
    envFrom:
      # whole files of envs
      - configMapRef:
          name: nameOfConfigMap
      - secretRef:
          name: nameOfSecret
```
instead of:
```yaml
    env:
      # single reference dynamic
      - name: SECRET_ENV_EXAMPLE_1
        valueFrom:
          secretKeyRef:
            key: my-secret-name
            name: my-secret-key-1
      - name: SECRET_ENV_EXAMPLE_2
        valueFrom:
          secretKeyRef:
            key: my-secret-name
            name: my-secret-key-2
      - name: SECRET_ENV_EXAMPLE_3
        valueFrom:
          secretKeyRef:
            key: my-secret-name
            name: my-secret-key-3

```

_Originally posted by @langehm in https://github.com/it-at-m/helm-charts/issues/87#issuecomment-2813022951_
